apiVersion: v1
kind: Service
metadata:
  name: testservice
  labels:
    environment: {{ .Values.env }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: foo
