apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jimmyjones2/applicationset.git
        revision: HEAD
        files:
        - path: "config/*/*.yaml"
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        helm:
          parameters:
          - name: test-param
            value: tesl-value
          values: |
            {{values}}
            {{values_key}}: *sta
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{applicationPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
