apiVersion: v1
kind: Service
metadata:
  name: testservice-subchart1
  labels:
    suffix: {{ .Values.global.suffix }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.dessert }}
