name: myapp
repoURL: https://github.com/jimmyjones2/applicationset.git
targetRevision: HEAD
applicationPath: apps/myapp
values_key: myapp
values: |
  myapp.image: docker.io/foobar:latest
  prod: &prod
    env: production
    foo: baz
    app: myapp
  dev: &dev
    <<: *prod
    env: development
  sta: &sta
    <<: *prod
    env: staging
