name: myapp
repoURL: https://github.com/jimmyjones2/applicationset.git
targetRevision: HEAD
applicationPath: apps/myapp
values_key: myapp
values: |
  prod: &prod
    env: prod
    foo: baz
    app: myapp
  dev: &dev
    <<: *prod
    env: dev
  sta: &sta
    <<: *prod
    env: prod
