aws_account: 123456
asset_id: 11223344
cluster:
  owner: "cluster-admin@company.com"
  name: "engineering-staging"
  address: "http://1.2.3.4"
empty: null
emptys: ''
hv:
  common: |
    abc: def
    ghi: hij
  staging: |
    abc: ggg
values: |
  prod: &prod
    env: prod
    foo: baz
    app: myapp
  dev:
    <<: *prod
    env: dev
  sta:
    <<: *prod
    env: prod
