aws_account: 123456
asset_id: 11223344
cluster:
  owner: "cluster-admin@company.com"
  name: "engineering-staging"
  address: "http://1.2.3.4"
hv:
  common: |
    abc: def
    ghi: hij
  staging: |
    abc: ggg
